name: "ci"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - docs/
      - scripts/
      - .vscode/
      - .husky/
      - README.md
      - COPYING
      - renovate.json
      - .czrc.json
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .prettierignore

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', '.yarn', 'node_modules') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build astro
        run: yarn build
